# Generated by Django 3.2 on 2021-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
