# Generated by Django 3.2 on 2021-04-24 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=40)),
                ('writerName', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('number_of_enquiry', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 13, 22, 28, 230756))),
                ('is_published', models.BooleanField(default=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='genres', to='books.Genre')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_sellers.seller')),
            ],
        ),
    ]
