# Generated by Django 3.2 on 2021-04-24 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210424_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 13, 27, 7, 562371)),
        ),
    ]
