# Generated by Django 3.2 on 2021-04-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 14, 9, 29, 566657)),
        ),
    ]
