# Generated by Django 3.2 on 2021-04-24 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_list_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genre1',
        ),
        migrations.AddField(
            model_name='book',
            name='genre2',
            field=models.CharField(blank=True, choices=[('1', 'Motivational'), ('2', 'Fiction'), ('3', 'Business'), ('4', 'Children'), ('5', 'Health'), ('6', 'Story')], max_length=32),
        ),
        migrations.AddField(
            model_name='book',
            name='genre3',
            field=models.CharField(blank=True, choices=[('1', 'Motivational'), ('2', 'Fiction'), ('3', 'Business'), ('4', 'Children'), ('5', 'Health'), ('6', 'Story')], max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 14, 10, 9, 672884)),
        ),
    ]
