# Generated by Django 3.2 on 2021-04-28 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210424_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre1',
            field=models.CharField(blank=True, choices=[('Motivational', 'Motivational'), ('Fiction', 'Fiction'), ('Business', 'Business'), ('Children', 'Children'), ('Health', 'Health'), ('Story', 'Story'), ('Novel', 'Novel'), ('Fantasy', 'fantasy'), ('Comic', 'Comic'), ('Ronamce', 'Ronamce'), ('Adventure', 'Adventure'), ('Science', 'Science')], max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre2',
            field=models.CharField(blank=True, choices=[('Motivational', 'Motivational'), ('Fiction', 'Fiction'), ('Business', 'Business'), ('Children', 'Children'), ('Health', 'Health'), ('Story', 'Story'), ('Novel', 'Novel'), ('Fantasy', 'fantasy'), ('Comic', 'Comic'), ('Ronamce', 'Ronamce'), ('Adventure', 'Adventure'), ('Science', 'Science')], max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre3',
            field=models.CharField(blank=True, choices=[('Motivational', 'Motivational'), ('Fiction', 'Fiction'), ('Business', 'Business'), ('Children', 'Children'), ('Health', 'Health'), ('Story', 'Story'), ('Novel', 'Novel'), ('Fantasy', 'fantasy'), ('Comic', 'Comic'), ('Ronamce', 'Ronamce'), ('Adventure', 'Adventure'), ('Science', 'Science')], max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 28, 10, 54, 25, 248507)),
        ),
    ]
