# Generated by Django 3.1.7 on 2021-03-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messenger',
        ),
    ]
