# Generated by Django 3.1.7 on 2021-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20210331_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
