# Generated by Django 3.2 on 2021-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20210401_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
