# Generated by Django 3.2 on 2021-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_messenger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='age',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
